version: '3'
services:
  redis:
    image: 'redis:alpine'

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  cronotab:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/cronotab.pid && bundle exec crono"
    depends_on:
      - db

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - cronotab
