default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: course_app_development

test:
  <<: *default
  database: course_app_test

production:
  <<: *default
  database: course_app_production
  username: course_app
  password: <%= ENV['COURSE_APP_DATABASE_PASSWORD'] %>
